import matplotlib.pyplot as plt
f = open("tictactoe/resultsfinal/wins_starter.txt", "r")
text = f.read()
historywon = list(map(float, text[1:-1].split(", ")))
f = open("tictactoe/resultsfinal/losses_starter.txt", "r")
text = f.read()
historylosses = list(map(float, text[1:-1].split(", ")))
f = open("tictactoe/resultsfinal/draws_starter.txt", "r")
text = f.read()
historydraws = list(map(float, text[1:-1].split(", ")))
x = list(range(0,len(historywon)))
new_x = [i * 100 for i in x]
plt.ylim(top=100)
plt.ylim(bottom=0)
plt.ylabel('rate in %')
plt.xlabel('iteration')
plt.plot(new_x, historywon, color='green', label='win rate')
plt.plot(new_x, historydraws, color='blue', label='stalemate rate')
plt.plot(new_x, historylosses, color='red', label='loss rate')
plt.legend(loc='upper left')
plt.show()